"""
Bundled Together AI model catalog data.

This module holds only the generated registry snapshot (chat, language and
embedding model tables plus the snapshot date), refreshed from the live
Together API. Defaults, lookup helpers and the drift check live in
:mod:`effgen.models.together_models`, which re-exports every name defined
here; import from that module rather than from this one.
"""

from __future__ import annotations

# Date this bundled registry was last fetched from the Together API
REGISTRY_FETCH_DATE = "2026-07-19"

# ---------------------------------------------------------------------------
# Chat models (129 total as of 2026-07-19)
# Sorted by input price (ascending). Free/\$0 models listed first.
# ---------------------------------------------------------------------------
TOGETHER_MODELS: dict[str, dict] = {
    # Google — Gemma 4 E4B-it
    "google/gemma-4-E4B-it": {
        "family": "gemma-4",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Hcompany — Holo3 35B A3b
    "Hcompany/Holo3-35B-A3B": {
        "family": "holo",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Hcompany",
    },
    # Google — Gemma 4 26B A4b It
    "google/gemma-4-26B-A4B-it": {
        "family": "gemma-4",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Qwen — Qwen3 Coder 30B A3b Instruct
    "Qwen/Qwen3-Coder-30B-A3B-Instruct": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 32B
    "Qwen/Qwen2.5-32B": {
        "family": "qwen",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Google — Gemma 2 9B It
    "google/gemma-2-9b-it": {
        "family": "gemma",
        "context": 8192,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Llama — nim/meta/llama-3.1-70b-instruct
    "nim/meta/llama-3.1-70b-instruct": {
        "family": "llama",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Llama",
    },
    # Meta — nim/meta/llama-3.1-8b-instruct
    "nim/meta/llama-3.1-8b-instruct": {
        "family": "llama",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # NVIDIA — nim/nv-mistralai/mistral-nemo-12b-instruct
    "nim/nv-mistralai/mistral-nemo-12b-instruct": {
        "family": "mistral",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "NVIDIA",
    },
    # NVIDIA — nim/nvidia/llama-3.1-nemotron-70b-instruct
    "nim/nvidia/llama-3.1-nemotron-70b-instruct": {
        "family": "llama",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "NVIDIA",
    },
    # deepcogito — Cogito V1 Preview Llama 70B
    "deepcogito/cogito-v1-preview-llama-70B": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "deepcogito",
    },
    # deepcogito — Cogito V1 Preview Llama 70B Turbo
    "deepcogito/cogito-v1-preview-llama-70B-Turbo": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "deepcogito",
    },
    # Zai Org — GLM 5 Fp4
    "zai-org/GLM-5-FP4": {
        "family": "glm-5",
        "context": 202752,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Zai Org",
    },
    # Nvidia — Nemotron 3 Nano Omni 30B A3b Reasoning Fp8
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning-fp8": {
        "family": "nemotron",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Nvidia",
    },
    # deepcogito — Cogito V1 Preview Llama 8B
    "deepcogito/cogito-v1-preview-llama-8B": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "deepcogito",
    },
    # MiniMaxAI — MiniMax M2.5 FP4
    "MiniMaxAI/MiniMax-M2.5-FP4": {
        "family": "minimax",
        "context": 8192,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "MiniMaxAI",
    },
    # deepcogito — Cogito V1 Preview Qwen 14B
    "deepcogito/cogito-v1-preview-qwen-14B": {
        "family": "cogito",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "deepcogito",
    },
    # deepcogito — Cogito V1 Preview Qwen 32B
    "deepcogito/cogito-v1-preview-qwen-32B": {
        "family": "qwen-3",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "deepcogito",
    },
    # Deepseek — Deepseek OCR 2
    "deepseek-ai/DeepSeek-OCR-2": {
        "family": "deepseek",
        "context": 8192,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Deepseek",
    },
    # Google — Gemma 3 4b it
    "google/gemma-3-4b-it": {
        "family": "gemma-3",
        "context": 65536,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Deepseek — DeepSeek R1 Distill Qwen 7B
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B": {
        "family": "deepseek-r1",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Deepseek",
    },
    # Deepseek — Deepseek V3
    # Deepseek — Deepseek V3.1 Base
    # Deepseek — Deepseek V3.2 Exp
    # Meta — Llama 3.2 1B
    "meta-llama/Llama-3.2-1B": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Nvidia — Nvidia Nemotron 3 Super 120B A12b Fp8
    "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8": {
        "family": "nemotron",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Nvidia",
    },
    # Togethercomputer — Deepcoder 14B Preview
    "agentica-org/DeepCoder-14B-Preview": {
        "family": "deepcoder",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Togethercomputer",
    },
    # MiniMax — Minimax M1 40K
    "MiniMaxAI/MiniMax-M1-40k": {
        "family": "minimax",
        "context": 1048576,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "MiniMax",
    },
    # MiniMax — Minimax M1 80K
    "MiniMaxAI/MiniMax-M1-80k": {
        "family": "minimax",
        "context": 1048576,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "MiniMax",
    },
    # Qwen — Qwen2.5 1.5B
    "Qwen/Qwen2.5-1.5B": {
        "family": "qwen",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 1.5B Instruct
    "Qwen/Qwen2.5-1.5B-Instruct": {
        "family": "qwen",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 14B
    "Qwen/Qwen2.5-14B": {
        "family": "qwen",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 3B Instruct
    "Qwen/Qwen2.5-3B-Instruct": {
        "family": "qwen",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 72B
    "Qwen/Qwen2.5-72B": {
        "family": "qwen",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 7B
    "Qwen/Qwen2.5-7B": {
        "family": "qwen",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 7B Instruct
    "Qwen/Qwen2.5-7B-Instruct": {
        "family": "qwen",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 0.6B
    "Qwen/Qwen3-0.6B": {
        "family": "qwen-3",
        "context": 40960,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 1.7B
    "Qwen/Qwen3-1.7B": {
        "family": "qwen-3",
        "context": 40960,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 235B A22B FP8
    # Qwen — Qwen3 8B
    "Qwen/Qwen3-8B": {
        "family": "qwen-3",
        "context": 40960,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 Next 80B A3b Instruct Fp8
    "Qwen/Qwen3-Next-80B-A3B-Instruct-FP8": {
        "family": "qwen-3",
        "context": 0,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3-VL-235B-A22B-Instruct-FP8
    "Qwen/Qwen3-VL-235B-A22B-Instruct-FP8": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Google — Gemma 3 27B Pt
    "google/gemma-3-27b-pt": {
        "family": "gemma-3",
        "context": 0,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Meta — meta-llama/Llama-2-7b-chat-hf
    "meta-llama/Llama-2-7b-chat-hf": {
        "family": "llama-2",
        "context": 4096,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Meta — nim/meta/llama-3.2-90b-vision-instruct
    "nim/meta/llama-3.2-90b-vision-instruct": {
        "family": "llama",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "supports_vision": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Qwen — Qwen3.5 397B A17b Fp8
    # Google — Gemma 2B It
    "google/gemma-2b-it": {
        "family": "gemma",
        "context": 8192,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Mistralai — Magistral Small 2506
    "mistralai/Magistral-Small-2506": {
        "family": "mistral",
        "context": 40960,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Mistralai",
    },
    # Mistralai — Mistral 7B v0.1
    "mistralai/Mistral-7B-v0.1": {
        "family": "mistral",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Mistralai",
    },
    # DeepSeek — DeepSeek R1 (Original)
    # Deepseek — Deepseek V3.1 Terminus
    # Qwen — Qwen3 30B A3B Instruct 2507 Lora
    "Qwen/Qwen3-30B-A3B-Instruct-2507-Lora": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 4B Instruct 2507
    "Qwen/Qwen3-4B-Instruct-2507": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 8B Lora
    "Qwen/Qwen3-8B-Lora": {
        "family": "qwen-3",
        "context": 40960,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Meta — Llama 3.1 405B
    "meta-llama/Llama-3.1-405B": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Meta — Llama 3.1 70B
    "meta-llama/Meta-Llama-3.1-70B": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Deepseek — Deepseek V3.2
    # Meta — Llama 4 Maverick 17B 128E
    # Mistral — nim/mistralai/mixtral-8x22b-instruct-v01
    "nim/mistralai/mixtral-8x22b-instruct-v01": {
        "family": "mistral",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Mistral",
    },
    # Meta — Meta Llama 3.1 8B Instruct Awq Int4
    "togethercomputer/meta-llama-3.1-8B-Instruct-AWQ-INT4": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Zai Org — GLM 4.5V
    "zai-org/GLM-4.5V": {
        "family": "glm-4",
        "context": 65536,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Zai Org",
    },
    # Zai Org — GLM OCR
    "zai-org/GLM-OCR": {
        "family": "glm",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Zai Org",
    },
    # MiniMaxAI — MiniMax M2
    "MiniMaxAI/MiniMax-M2": {
        "family": "minimax",
        "context": 196608,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "MiniMaxAI",
    },
    # Google — Gemma 4 E2B-it
    "google/gemma-4-E2B-it": {
        "family": "gemma-4",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Qwen — Qwen3.6 35B A3b Fp8
    "Qwen/Qwen3.6-35B-A3B-FP8": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Nvidia — Nvidia Nemotron 3 Super 120B A12b Bf16
    "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16": {
        "family": "nemotron",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Nvidia",
    },
    # Qwen — Qwen3.5 122B A10b Fp8
    "Qwen/Qwen3.5-122B-A10B-FP8": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 30B A3b
    "Qwen/Qwen3-30B-A3B": {
        "family": "qwen-3",
        "context": 40960,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Google — Gemma 3 1b it
    "google/gemma-3-1b-it": {
        "family": "gemma-3",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Google — Gemma 3 270M It
    "google/gemma-3-270m-it": {
        "family": "gemma-3",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Meta — Llama 4 Scout (17Bx16E)
    "meta-llama/Llama-4-Scout-17B-16E": {
        "family": "llama-4",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Mistralai — Devstral Small 2505
    "mistralai/Devstral-Small-2505": {
        "family": "mistral",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Mistralai",
    },
    # Mistralai — Mixtral 8X22b Instruct V0.1
    "mistralai/Mixtral-8x22B-Instruct-v0.1": {
        "family": "mistral",
        "context": 65536,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Mistralai",
    },
    # Nvidia — nim/meta/llama-3.2-11b-vision-instruct
    "nim/meta/llama-3.2-11b-vision-instruct": {
        "family": "llama",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "supports_vision": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Nvidia",
    },
    # Meta — nim/meta/llama-3.3-70b-instruct
    "nim/meta/llama-3.3-70b-instruct": {
        "family": "llama",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # mistralai — nim/mistralai/mixtral-8x7b-instruct-v01
    "nim/mistralai/mixtral-8x7b-instruct-v01": {
        "family": "mistral",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "mistralai",
    },
    # Sarvamai — Sarvam M
    "sarvamai/sarvam-m": {
        "family": "sarvam",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Sarvamai",
    },
    # Essential AI — EssentialAI Rnj-1 Instruct
    "togethercomputer/EssentialAI-RNJ-1-Instruct": {
        "family": "essentialai",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Essential AI",
    },
    # Nvidia — Nvidia Nemotron 3 Nano 30B A3b Bf16
    "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16": {
        "family": "nemotron",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Nvidia",
    },
    # Nvidia — nim/nvidia/llama-3.3-nemotron-super-49b-v1
    "nim/nvidia/llama-3.3-nemotron-super-49b-v1": {
        "family": "llama",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Nvidia",
    },
    # Qwen — Qwen3.5 9B Fp8
    "Qwen/Qwen3.5-9B-FP8": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3.5 35B A3b
    "Qwen/Qwen3.5-35B-A3B": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.0,
        "pricing_per_1m_output": 0.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen 2 Instruct (1.5B)
    "Qwen/Qwen2-1.5B-Instruct": {
        "family": "qwen",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.02,
        "pricing_per_1m_output": 0.02,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # OpenAI — OpenAI GPT-OSS 20B
    "openai/gpt-oss-20b": {
        "family": "gpt-oss",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": True,
        "pricing_per_1m_input": 0.05,
        "pricing_per_1m_output": 0.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "OpenAI",
    },
    # Google — Gemma 3N E4B Instruct
    "google/gemma-3n-E4B-it": {
        "family": "gemma-3",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": True,
        "pricing_per_1m_input": 0.060000000000000005,
        "pricing_per_1m_output": 0.12000000000000001,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Meta — Meta Llama 3.2 1B Instruct
    "meta-llama/Llama-3.2-1B-Instruct": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.060000000000000005,
        "pricing_per_1m_output": 0.060000000000000005,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Nvidia — Nvidia Nemotron Nano 9B V2
    "nvidia/NVIDIA-Nemotron-Nano-9B-v2": {
        "family": "nemotron",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.060000000000000005,
        "pricing_per_1m_output": 0.25,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Nvidia",
    },
    # Qwen — Qwen3.5 9B FP8
    "Qwen/Qwen3.5-9B": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": True,
        "pricing_per_1m_input": 0.1,
        "pricing_per_1m_output": 0.15,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Togethercomputer — Arize AI Qwen 2 1.5B Instruct
    "arize-ai/qwen-2-1.5b-instruct": {
        "family": "arize",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": True,
        "pricing_per_1m_input": 0.1,
        "pricing_per_1m_output": 0.1,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Togethercomputer",
    },
    # mistralai — Mistral Small (24B) Instruct 25.01
    "mistralai/Mistral-Small-24B-Instruct-2501": {
        "family": "mistral",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.1,
        "pricing_per_1m_output": 0.3,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "mistralai",
    },
    # OpenAI — OpenAI GPT-OSS 120B
    "openai/gpt-oss-120b": {
        "family": "gpt-oss",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": True,
        "pricing_per_1m_input": 0.15,
        "pricing_per_1m_output": 0.6,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "OpenAI",
    },
    # Qwen — Qwen3 Next 80B A3b Thinking
    "Qwen/Qwen3-Next-80B-A3B-Thinking": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.15,
        "pricing_per_1m_output": 1.5,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 Next 80B A3b Instruct
    "Qwen/Qwen3-Next-80B-A3B-Instruct": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.15,
        "pricing_per_1m_output": 1.5,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3-VL-8B-Instruct
    "Qwen/Qwen3-VL-8B-Instruct": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.18000000000000002,
        "pricing_per_1m_output": 0.68,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # DeepSeek — DeepSeek R1 Distill Qwen 1.5B
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B": {
        "family": "deepseek-r1",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.18000000000000002,
        "pricing_per_1m_output": 0.18000000000000002,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "DeepSeek",
    },
    # Meta — Meta Llama 3.1 8B Instruct Turbo
    "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.18000000000000002,
        "pricing_per_1m_output": 0.18000000000000002,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Meta — Llama 4 Scout Instruct (17Bx16E)
    "meta-llama/Llama-4-Scout-17B-16E-Instruct": {
        "family": "llama-4",
        "context": 1048576,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.18000000000000002,
        "pricing_per_1m_output": 0.5900000000000001,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Google — Gemma 4 31B-it FP8
    "google/gemma-4-31B-it": {
        "family": "gemma-4",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": True,
        "pricing_per_1m_input": 0.2,
        "pricing_per_1m_output": 0.5,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Zai Org — Glm 4.5 Air Fp8
    "zai-org/GLM-4.5-Air-FP8": {
        "family": "glm-4",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.2,
        "pricing_per_1m_output": 1.1,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Zai Org",
    },
    # mistralai — Mistral (7B) Instruct v0.1
    "mistralai/Mistral-7B-Instruct-v0.1": {
        "family": "mistral",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.2,
        "pricing_per_1m_output": 0.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "mistralai",
    },
    # Meta — Meta Llama 3 8B Instruct
    "meta-llama/Meta-Llama-3-8B-Instruct": {
        "family": "llama",
        "context": 8192,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.2,
        "pricing_per_1m_output": 0.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Mistralai — Ministral 3 14B Instruct 2512
    "mistralai/Ministral-3-14B-Instruct-2512": {
        "family": "mistral",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.2,
        "pricing_per_1m_output": 0.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Mistralai",
    },
    # mistralai — Mistral (7B) Instruct v0.3
    "mistralai/Mistral-7B-Instruct-v0.3": {
        "family": "mistral",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.2,
        "pricing_per_1m_output": 0.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "mistralai",
    },
    # Meta — Meta Llama 3 8B Instruct Reference
    "meta-llama/Llama-3-8b-chat-hf": {
        "family": "llama",
        "context": 8192,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.2,
        "pricing_per_1m_output": 0.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Meta — Llama 4 Maverick Instruct (17Bx128E) FP8
    # MiniMaxAI — MiniMax M2.7 FP4
    "MiniMaxAI/MiniMax-M2.7": {
        "family": "minimax",
        "context": 196608,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": True,
        "pricing_per_1m_input": 0.3,
        "pricing_per_1m_output": 1.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "MiniMaxAI",
    },
    # MiniMaxAI — MiniMax M2.5 FP4
    # Qwen — Qwen2.5 7B Instruct Turbo
    "Qwen/Qwen2.5-7B-Instruct-Turbo": {
        "family": "qwen",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": True,
        "pricing_per_1m_input": 0.3,
        "pricing_per_1m_output": 0.3,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Zai Org — GLM 4.7 Fp8
    "zai-org/GLM-4.7": {
        "family": "glm-4",
        "context": 202752,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.45,
        "pricing_per_1m_output": 2.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Zai Org",
    },
    # Moonshot AI — Kimi K2.5
    # Qwen — Qwen3 Coder Next Fp8
    "Qwen/Qwen3-Coder-Next-FP8": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.5,
        "pricing_per_1m_output": 1.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3.6 Plus
    "Qwen/Qwen3.6-Plus": {
        "family": "qwen-3",
        "context": 1000000,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.5,
        "pricing_per_1m_output": 3.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3-VL-32B-Instruct
    "Qwen/Qwen3-VL-32B-Instruct": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.5,
        "pricing_per_1m_output": 1.5,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3.5 397B A17b
    "Qwen/Qwen3.5-397B-A17B": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 0.6,
        "pricing_per_1m_output": 3.6,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # DeepSeek — Deepseek V3.1
    "deepseek-ai/DeepSeek-V3.1": {
        "family": "deepseek-v3",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.6,
        "pricing_per_1m_output": 1.7,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "DeepSeek",
    },
    # Nousresearch — Nous Hermes 2 Mixtral 8X7B Dpo
    "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO": {
        "family": "mistral",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.6,
        "pricing_per_1m_output": 0.6,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Nousresearch",
    },
    # Zai Org — GLM 4.6 Fp8
    "zai-org/GLM-4.6": {
        "family": "glm-4",
        "context": 202752,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.6,
        "pricing_per_1m_output": 2.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Zai Org",
    },
    # mistralai — Mixtral-8x7B Instruct v0.1
    "mistralai/Mixtral-8x7B-Instruct-v0.1": {
        "family": "mistral",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.6,
        "pricing_per_1m_output": 0.6,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "mistralai",
    },
    # Qwen — Qwen3 235B A22B Thinking 2507 FP8
    # Deepseek — Deepseek Coder 33B Instruct
    "deepseek-ai/deepseek-coder-33b-instruct": {
        "family": "deepseek",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.8,
        "pricing_per_1m_output": 0.8,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Deepseek",
    },
    # Qwen — Qwen 2.5 Coder 32B Instruct
    "Qwen/Qwen2.5-Coder-32B-Instruct": {
        "family": "qwen",
        "context": 16384,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.8,
        "pricing_per_1m_output": 0.8,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen 2.5 14B Instruct
    "Qwen/Qwen2.5-14B-Instruct": {
        "family": "qwen",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.8,
        "pricing_per_1m_output": 0.8,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Google — Gemma-2 Instruct (27B)
    "google/gemma-2-27b-it": {
        "family": "gemma",
        "context": 8192,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.8,
        "pricing_per_1m_output": 0.8,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Google",
    },
    # Meta — Meta Llama 3.3 70B Instruct Turbo
    "meta-llama/Llama-3.3-70B-Instruct-Turbo": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": True,
        "pricing_per_1m_input": 0.88,
        "pricing_per_1m_output": 0.88,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Meta — Meta Llama 3.1 70B Instruct Turbo
    "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.88,
        "pricing_per_1m_output": 0.88,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # Meta — Meta Llama 3 70B Instruct Turbo
    "meta-llama/Meta-Llama-3-70B-Instruct-Turbo": {
        "family": "llama",
        "context": 8192,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.88,
        "pricing_per_1m_output": 0.88,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
    # nvidia — Llama 3.1 Nemotron 70B Instruct HF
    "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF": {
        "family": "llama",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 0.88,
        "pricing_per_1m_output": 0.88,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "nvidia",
    },
    # Zai Org — GLM 5 Fp4
    "zai-org/GLM-5": {
        "family": "glm-5",
        "context": 202752,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 1.0,
        "pricing_per_1m_output": 3.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Zai Org",
    },
    # Moonshot AI — Kimi K2.6 Fp4
    "moonshotai/Kimi-K2.6": {
        "family": "kimi",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": True,
        "pricing_per_1m_input": 1.2,
        "pricing_per_1m_output": 4.5,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Moonshot AI",
    },
    # Moonshot AI — Kimi K2 Thinking
    # Qwen — Qwen QwQ-32B
    "Qwen/QwQ-32B": {
        "family": "qwen",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 1.2,
        "pricing_per_1m_output": 1.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 72B Instruct
    "Qwen/Qwen2.5-72B-Instruct": {
        "family": "qwen",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 1.2,
        "pricing_per_1m_output": 1.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2.5 72B Instruct Turbo
    "Qwen/Qwen2.5-72B-Instruct-Turbo": {
        "family": "qwen",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 1.2,
        "pricing_per_1m_output": 1.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen2-VL (72B) Instruct
    "Qwen/Qwen2-VL-72B-Instruct": {
        "family": "qwen-vl",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 1.2,
        "pricing_per_1m_output": 1.2,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Deepcogito — Cogito v2.1 671B
    "deepcogito/cogito-v2-1-671b": {
        "family": "cogito",
        "context": 163840,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": True,
        "pricing_per_1m_input": 1.25,
        "pricing_per_1m_output": 1.25,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Deepcogito",
    },
    # Deepseek — Deepseek V3 0324
    # Zai Org — GLM 5.1 FP4
    "zai-org/GLM-5.1": {
        "family": "glm-5",
        "context": 202752,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 1.4,
        "pricing_per_1m_output": 4.4,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Zai Org",
    },
    # DeepSeek — DeepSeek R1 Distill Qwen 14B
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": {
        "family": "deepseek-r1",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 1.6,
        "pricing_per_1m_output": 1.6,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "DeepSeek",
    },
    # Qwen — Qwen2.5-VL (72B) Instruct
    "Qwen/Qwen2.5-VL-72B-Instruct": {
        "family": "qwen-vl",
        "context": 32768,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 1.95,
        "pricing_per_1m_output": 8.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # Qwen — Qwen3 Coder 480B A35B Instruct Fp8
    "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8": {
        "family": "qwen-3",
        "context": 262144,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 2.0,
        "pricing_per_1m_output": 2.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Qwen",
    },
    # DeepSeek — DeepSeek R1 Distill Llama 70B
    "deepseek-ai/DeepSeek-R1-Distill-Llama-70B": {
        "family": "llama",
        "context": 131072,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 2.0,
        "pricing_per_1m_output": 2.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "DeepSeek",
    },
    # Deepseek AI — Deepseek V4 Pro
    "deepseek-ai/DeepSeek-V4-Pro": {
        "family": "deepseek-v4",
        "context": 512000,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": True,
        "pricing_per_1m_input": 2.1,
        "pricing_per_1m_output": 4.4,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Deepseek AI",
    },
    # DeepSeek — DeepSeek R1-0528
    # Deepseek — DeepSeek R1 0528
    "deepseek-ai/DeepSeek-R1-0528": {
        "family": "deepseek-r1",
        "context": 163840,
        "max_output": 4_096,
        "supports_native_tools": True,
        "supports_streaming": True,
        "reasoning": True,
        "serverless": False,
        "pricing_per_1m_input": 3.0,
        "pricing_per_1m_output": 7.0,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Deepseek",
    },
    # Meta — Meta Llama 3.1 405B Instruct
    "meta-llama/Llama-3.1-405B-Instruct": {
        "family": "llama",
        "context": 4096,
        "max_output": 4_096,
        "supports_native_tools": False,
        "supports_streaming": True,
        "serverless": False,
        "pricing_per_1m_input": 3.5,
        "pricing_per_1m_output": 3.5,
        "rpm": 100,
        "tpm": 100_000,
        "active": True,
        "modality": "chat",
        "organization": "Meta",
    },
}

# ---------------------------------------------------------------------------
# Language models (base / completion, 13 total as of 2026-04-28)
# These are NOT instruction-tuned and don't support chat completions.
# ---------------------------------------------------------------------------
TOGETHER_LANGUAGE_MODELS: dict[str, dict] = {
    "Qwen/Qwen3-4B-Base": {"family": "qwen-3", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "Qwen/Qwen2-1.5B": {"family": "qwen", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "deepseek-ai/DeepSeek-V3-Base": {"family": "deepseek-v3", "context": 0, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Deepseek"},
    "Qwen/Qwen2-72B": {"family": "qwen", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "Qwen/Qwen2-7B": {"family": "qwen", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "Qwen/Qwen3-0.6B-Base": {"family": "qwen-3", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "Qwen/Qwen3-1.7B-Base": {"family": "qwen-3", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "Qwen/Qwen3-14B-Base": {"family": "qwen-3", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "Qwen/Qwen3-30B-A3B-Base": {"family": "qwen-3", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "Qwen/Qwen3-8B-Base": {"family": "qwen-3", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Qwen"},
    "meta-llama/Llama-3.2-3B": {"family": "llama", "context": 131072, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "Meta"},
    "mistralai/Mixtral-8x7B-v0.1": {"family": "mistral", "context": 32768, "pricing_per_1m_input": 0.0, "pricing_per_1m_output": 0.0, "modality": "language", "organization": "mistralai"},
    "meta-llama/Meta-Llama-3.1-8B": {"family": "llama", "context": 16384, "pricing_per_1m_input": 0.2, "pricing_per_1m_output": 0.2, "modality": "language", "organization": "Meta"},
}

# ---------------------------------------------------------------------------
# Embedding models
# ---------------------------------------------------------------------------
TOGETHER_EMBEDDING_MODELS: dict[str, dict] = {
    "intfloat/multilingual-e5-large-instruct": {"context": 514, "pricing_per_1m_input": 0.02, "modality": "embedding", "organization": "Intfloat"},
}
