// Copies the documentation's route list out to where the landing site can read it.
//
// The 72 documentation pages are routes of a separate single-page app, so
// `app/sitemap.ts` cannot see them: `effgen-docs/` is outside the landing site's
// TypeScript project on purpose. Without this the sitemap would list eleven
// pages and omit the documentation entirely.
//
// `effgen-docs/src/nav.ts` stays the one place the table of contents is written
// down; this reads it and writes the paths and titles beside the counts in
// `data/`, which both halves of the site already share.
//
// The retired addresses in `REDIRECTS` are written out beside them. They are not
// sitemap entries — a retired address should not be advertised — but a static
// host still has to answer them with the documentation shell, or a bookmark to
// one lands on the host's 404 before the router can redirect it.
//
// Run by `npm run build` at the repository root, before the landing site builds.
//
//   node scripts/gen_docs_routes.mjs           write data/docsRoutes.json
//   node scripts/gen_docs_routes.mjs --check   fail if it is out of date

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = join(here, '..')
const NAV = join(ROOT, 'effgen-docs', 'src', 'nav.ts')
const OUT = join(ROOT, 'data', 'docsRoutes.json')

const source = readFileSync(NAV, 'utf8')

// Each entry is written as `path: '/x',` followed by `title: '...',`. Reading
// them as a pair rather than separately means a mismatched count is a parse
// failure rather than a silently short list.
const entries = []
for (const m of source.matchAll(/path:\s*'([^']+)',\s*\n\s*title:\s*'((?:[^'\\]|\\.)*)',/g)) {
  entries.push({ path: m[1], title: m[2].replace(/\\'/g, "'") })
}

// `path:` also appears in the interface that declares the shape, which carries
// no title after it — so the two counts differ by exactly that one declaration.
const declared = [...source.matchAll(/^\s*path:\s*'/gm)].length
if (entries.length !== declared) {
  console.error(
    `nav.ts has ${declared} route paths but ${entries.length} parsed with a title. ` +
    `Whatever changed shape in nav.ts has to be matched here before the sitemap is right.`
  )
  process.exit(1)
}

// The retired addresses, read from the same file. Each is a route the app
// answers with a redirect, so it needs a file to be served from wherever the
// site is hosted without a single-page-app fallback.
const redirects = []
const redirectBlock = source.match(/export const REDIRECTS[^{]*\{([^}]*)\}/)
if (!redirectBlock) {
  console.error('nav.ts no longer declares REDIRECTS in a shape this can read.')
  process.exit(1)
}
for (const m of redirectBlock[1].matchAll(/'([^']+)':\s*'([^']+)'/g)) {
  redirects.push({ path: m[1], to: m[2] })
}

const generated =
  JSON.stringify(
    {
      _comment:
        'Generated by scripts/gen_docs_routes.mjs from effgen-docs/src/nav.ts. ' +
        'Do not edit: add a page to nav.ts and re-run the generator.',
      base: '/docs',
      pages: entries,
      redirects,
    },
    null,
    2
  ) + '\n'

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {
    /* missing counts as out of date */
  }
  if (current !== generated) {
    console.error('data/docsRoutes.json is out of date — run node scripts/gen_docs_routes.mjs')
    process.exit(1)
  }
  console.log(
    `data/docsRoutes.json up to date (${entries.length} pages, ${redirects.length} retired addresses)`
  )
} else {
  writeFileSync(OUT, generated)
  console.log(
    `wrote data/docsRoutes.json — ${entries.length} pages, ${redirects.length} retired addresses`
  )
}
